#######################################################################
# Program:
#     Week 10, Maps
#     Brother Ercanbrack, CS235
# Author:
#     James Call
# Summary:
#     this code uses maps to calculate the frequency of words
#		in a text file
# Time:
#     1.5 hours
###############################################################

##############################################################
# The main rule
##############################################################
a.out: week10.o
	g++ -o a.out week10.o 
	tar -cf week10.tar *.cpp makefile
##############################################################
# The individual components
#     week10.o 
##############################################################
week10.o: week10.cpp
	g++ -c week10.cpp 